<a href="https://colab.research.google.com/github/asrinivasan75/CariesClassification/blob/main/DentalImageCNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Cell 1: Import Libraries
import os
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import confusion_matrix
import numpy as np


In [ ]:
# Cell 2: Define Directory Paths
base_dir = '/content/drive/MyDrive/Dental_Model'
nocaries_dir = os.path.join(base_dir, 'NoCaries')
cariesenamel_dir = os.path.join(base_dir, 'CariesEnamel')
cariesdentine_dir = os.path.join(base_dir, 'CariesDentine')


In [ ]:
# Cell 3: Set up Image Data Generator with Augmentation
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2
)

In [ ]:
# Cell 4: Multi-Class Model Setup
# Training and validation generators for Multi-Class Classification
train_generator = train_datagen.flow_from_directory(
    base_dir,
    target_size=(150, 150),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

validation_generator = train_datagen.flow_from_directory(
    base_dir,
    target_size=(150, 150),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)


Found 21 images belonging to 3 classes.
Found 5 images belonging to 3 classes.


In [ ]:
# Cell 5: Define the Multi-Class Model
model_multi = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)),
    MaxPooling2D(pool_size=(2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(pool_size=(2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(pool_size=(2, 2)),
    Flatten(),
    Dense(512, activation='relu'),
    Dropout(0.5),
    Dense(3, activation='softmax')  # Multi-class output
])

model_multi.compile(optimizer=Adam(learning_rate=0.001),
                    loss='categorical_crossentropy',
                    metrics=['accuracy'])


/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [18]:
# Cell 6: Train the Multi-Class Model
history_multi = model_multi.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // train_generator.batch_size,
    validation_data=validation_generator,
    validation_steps=validation_generator.samples // validation_generator.batch_size,
    epochs=10
)


Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


1/1 ━━━━━━━━━━━━━━━━━━━━ 11s 11s/step - accuracy: 0.3333 - loss: 1.0955 - val_accuracy: 0.4000 - val_loss: 1.7260
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.3810 - loss: 1.9557 - val_accuracy: 0.4000 - val_loss: 1.9723
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.3810 - loss: 2.1494 - val_accuracy: 0.2000 - val_loss: 1.2974
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.1429 - loss: 1.5190 - val_accuracy: 0.2000 - val_loss: 1.1452
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.2381 - loss: 1.1427 - val_accuracy: 0.4000 - val_loss: 1.0887
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.3810 - loss: 1.1118 - val_accuracy: 0.4000 - val_loss: 1.0649
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.3810 - loss: 1.0801 - val_accuracy: 0.4000 - val_loss: 1.0577
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.3810 - loss: 1.0731 - val_accuracy: 0.4000 - val_loss: 1.0541
Epoch 9/10
1/1 ━━━━━━━━━━

In [25]:
# Cell 7: Multi-Class Confusion Matrix and TP, TN, FP, FN Calculation
val_labels_multi = validation_generator.classes  # Actual labels
predictions_multi = np.argmax(model_multi.predict(validation_generator), axis=1)

# Compute confusion matrix
conf_matrix_multi = confusion_matrix(val_labels_multi, predictions_multi)

# Display the confusion matrix
print("Multi-Class Model Confusion Matrix:")
print(conf_matrix_multi)

# Calculate TP, TN, FP, FN for each class
num_classes = conf_matrix_multi.shape[0]
tp = {}
tn = {}
fp = {}
fn = {}

for i in range(num_classes):
    # True Positives (TP): Correct predictions for the class
    tp[i] = conf_matrix_multi[i, i]

    # False Positives (FP): Sum of the predictions for the class minus TP
    fp[i] = conf_matrix_multi[:, i].sum() - tp[i]

    # False Negatives (FN): Sum of the actual instances of the class minus TP
    fn[i] = conf_matrix_multi[i, :].sum() - tp[i]

    # True Negatives (TN): Sum of all entries in the matrix, excluding current row and column
    tn[i] = conf_matrix_multi.sum() - (fp[i] + fn[i] + tp[i])

# Output TP, TN, FP, FN for each class
for i, class_name in enumerate(validation_generator.class_indices.keys()):
    print(f"\nClass '{class_name}':")
    print(f"  True Positives (TP): {tp[i]}")
    print(f"  True Negatives (TN): {tn[i]}")
    print(f"  False Positives (FP): {fp[i]}")
    print(f"  False Negatives (FN): {fn[i]}")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 476ms/step
Multi-Class Model Confusion Matrix:
[[2 0 0]
 [1 0 0]
 [2 0 0]]

Class 'CariesDentine':
  True Positives (TP): 2
  True Negatives (TN): 0
  False Positives (FP): 3
  False Negatives (FN): 0

Class 'CariesEnamel':
  True Positives (TP): 0
  True Negatives (TN): 4
  False Positives (FP): 0
  False Negatives (FN): 1

Class 'NoCaries':
  True Positives (TP): 0
  True Negatives (TN): 3
  False Positives (FP): 0
  False Negatives (FN): 2


In [26]:
# Cell 8: Binary Model Setup
# Training and validation generators for Binary Classification: "No Caries" vs "Caries in Dentine"
binary_train_generator = train_datagen.flow_from_directory(
    base_dir,
    classes=['NoCaries', 'CariesDentine'],
    target_size=(150, 150),
    batch_size=32,
    class_mode='binary',
    subset='training'
)

binary_validation_generator = train_datagen.flow_from_directory(
    base_dir,
    classes=['NoCaries', 'CariesDentine'],
    target_size=(150, 150),
    batch_size=32,
    class_mode='binary',
    subset='validation'
)


Found 16 images belonging to 2 classes.
Found 4 images belonging to 2 classes.


In [27]:
# Cell 9: Define the Binary Classification Model
model_binary = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)),
    MaxPooling2D(pool_size=(2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(pool_size=(2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(pool_size=(2, 2)),
    Flatten(),
    Dense(512, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')  # Single output for binary classification
])

model_binary.compile(optimizer=Adam(learning_rate=0.001),
                     loss='binary_crossentropy',
                     metrics=['accuracy'])


/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [30]:
# Cell 10: Train the Binary Model
history_binary = model_binary.fit(
    binary_train_generator,
    steps_per_epoch=binary_train_generator.samples // binary_train_generator.batch_size,
    validation_data=binary_validation_generator,
    validation_steps=binary_validation_generator.samples // binary_validation_generator.batch_size,
    epochs=10
)


Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5625 - loss: 0.7001 - val_accuracy: 0.5000 - val_loss: 0.6926
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5625 - loss: 0.6909 - val_accuracy: 0.5000 - val_loss: 0.6956
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.6973 - val_accuracy: 0.5000 - val_loss: 0.6943
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5000 - loss: 0.6835 - val_accuracy: 0.5000 - val_loss: 0.6937
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5625 - loss: 0.6967 - val_accuracy: 0.5000 - val_loss: 0.6922
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.3750 - loss: 0.7151 - val_accuracy: 0.5000 - val_loss: 0.6937
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.4375 - loss: 0.7003 - val_accuracy: 0.5000 - val_loss: 0.6942
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.4375 - loss: 0.7136 - val_accuracy: 0.5000 - val_loss: 0.6942
Epoch 9/10
1/1 ━

In [31]:
# Cell 11: Binary Confusion Matrix
val_labels_binary = binary_validation_generator.classes
predictions_binary = (model_binary.predict(binary_validation_generator) > 0.5).astype("int32").flatten()
tn_binary, fp_binary, fn_binary, tp_binary = confusion_matrix(val_labels_binary, predictions_binary).ravel()

# Output Binary Results
print("Binary Classification Model:")
print(f'True Positives (TP): {tp_binary}')
print(f'True Negatives (TN): {tn_binary}')
print(f'False Positives (FP): {fp_binary}')
print(f'False Negatives (FN): {fn_binary}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step
Binary Classification Model:
True Positives (TP): 0
True Negatives (TN): 2
False Positives (FP): 0
False Negatives (FN): 2
